### ISSUE TITLE
Why i can't upload a blog to db?

### ISSUE THREAD

**Issue by csunking** [754594774/TF-Blog#1]
不知道作者您是否自己亲自测试过。首先数据库中没有admin，所以没法登录。建议您有空时，写个单元测试程序。让别人好向数据库中添加用户。
此外，这个项目我个人还是比较喜欢的。希望使之更完善。备注，我是新手。

**Comment by csunking** [comment]
自己给自己解答下。这个周末，已经修复完成，可以初步的运行了。主要是源代码中的数据库的某些表的字段信息缺失，导致在程序操作数据库时，一直报“HTTP Status 405 – Method Not Allowed”错误，而且原来的代码中的js脚本也有很多错误，比如form的id写错了，感觉原代码很随意。对初学者来讲坑太多，太浪费时间。有交流讨论的，请联系我。

**Comment by 754594774** [comment]
前后端分离是现今比较流行的方式，我当时写博客的时候也想赶下时髦，后来在实际的运用中，我发现前后端分离确实又很多优点，但是工作量也大了很多很多，我不想在前端投入太多精力，所以最终还是换成了jsp,这个angularjs版本我应该不会更新了，有兴趣的话可以看下jsp版本(www.linn.site/blog)

**Comment by csunking** [comment]
感觉不维护实在是太可惜了。
